name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pods
      run: pod install
    - name: Install fastlane
      run: bundle install
    - name: Install Simulator
      run: xcrun simctl create 'iPhone 11 (13.2)' com.apple.CoreSimulator.SimDeviceType.iPhone-11 com.apple.CoreSimulator.SimRuntime.iOS-13-2
    - name: Build and Run tests
      run: bundle exec fastlane tests
